/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_test_NativeTest_HelloWorld */

#ifndef _Included_my_test_NativeTest_HelloWorld
#define _Included_my_test_NativeTest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_test_NativeTest_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_my_test_NativeTest_HelloWorld_hello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
